### ISSUE TITLE
FSL intall issues  on MAC

### ISSUE THREAD

**Issue by sgengmail** [sgengmail/FSL-on-resting-state-connectivity#1]
_When I installed FSL on my own computer, there are two questions I met:_
cd ~/Downloads
python  fslinstaller.py
**File "fslinstaller.py", line 32, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)**
`export LC_ALL=C`
_then the second error occurs that :_

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
`export PYTHONHTTPSVERIFY=0`
**now everything works now!**

**Comment by gengshuangmail** [comment]
export LC_ALL=C
export PYTHONHTTPSVERIFY=0
solve the problem

**Comment by sgengmail** [comment]
export LC_ALL=C
export PYTHONHTTPSVERIFY=0
solve the problem
